apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      name: demo
    name: controllers
  spec:
    containers:
    - image: mongo
      name: mongo
      ports:
      - name: mongo
        containerPort: 27017
        hostPort: 27017
    - image: node:0.10.40
      command: ['/bin/sh', '-c']
      args: ['tail -f /dev/null']
      name: nodejs
      ports:
      - containerPort: 3000
        name: http-server
